src/mpDris2.in.py

If mpDris2 receives multiple pause command in a row, it toggles play pause.
I took a look and find that the `MPDClient.pause` function [toggles play/pause by default](https://pythonhosted.org/python-mpd2/topics/commands.html#MPDClient.pause).
I fixed it by calling `MPDClient.pause(1)` to always force pause.

Fix pause command toggles play/pause

---

src/mpDris2.in.py

With Gnome 3.16, the old(?) name stopped working for me. This change
fixes the problem for me. I kept a fallback for the old name.

Use new GSD.MediaKeys bus name

---

src/mpDris2.in.py

If mpDris2 is started with no implementation of o.fd.Notifications
available, it might as well gracefully continue to work without that
feature.
Bug-Debian: https://bugs.debian.org/830816
Signed-off-by: Simon McVittie <smcv@debian.org>

Make failure to update notifications non-fatal

---

src/mpDris2.in.py

mpDris2 uses private methods of the MPDClient, which have changed
between 0.5.5 and 1.0.0 to support the new async APIs using asyncio
and Twisted. Add support for yet another version.
Bug-Debian: https://bugs.debian.org/891416
Signed-off-by: Simon McVittie <smcv@debian.org>

Add compatibility with python-mpd2 1.0.0

---

src/mpDris2.in.py

Before initializing notifications check that
org.freedesktop.Notifications is available on the bus.
Refs #109

Check org.freedesktop.Notifications

---

src/mpDris2.in.py

If mpDris2 started too early in the desktop environment, a notification
service could still be unavailable.
Now if the config says there should be notifications, everytime we have
to display a notification, we retry to connect to a notifications
service if we haven't already

Retry to acquire a notification service

---

src/mpDris2.in.py
src/org.mpris.MediaPlayer2.mpd.service.in

The systemd journal already includes timestamps, making them redundant in the message content

Don't timestamp messages when logging to systemd journal

---

src/mpDris2.in.py

It's admittedly trivial and kind of pointless, but the `__getattr__` implementation for `MPDWrapper` defines a function `fn` (which does nothing but `return self.call(...)`), the immediately returns `fn` to its own caller.
Since it's never called by that name, `fn` is effectively an anonymous function. The whole thing can be done in one line with a `lambda` expression, instead of requiring three lines to implement.

Implement __getattr__ via lambda expresion

---

src/mpDris2.in.py
src/org.mpris.MediaPlayer2.mpd.service.in

The `-j` / `--use-journal` switch replaces `-n`, and tells mpDris2 to _attempt_ direct journal logging. (Requires the `systemd.journal` Python module.) The `--use-journal` argument is added to the invocation in the systemd unit file.
Regular `sys.stderr` log output is used by default, and as a fallback if journald logging setup fails.
The `-d` flag is compatible with either logging method, so `mpDris2 -j -d` will direct debug logging to the journal.

Add optional systemd journal logging

---

src/mpDris2.in.py

[This bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1798356) came in via Fedora's Abrt reporting system. The pertinent details:
```
Truncated backtrace:
mpDris2:734:_update_properties:TypeError: 'bool' object is not subscriptable
Traceback (most recent call last):
File "/usr/bin/mpDris2", line 454, in timer_callback
self._update_properties(force=False)
File "/usr/bin/mpDris2", line 734, in _update_properties
if old_status['state'] != new_status['state']:
TypeError: 'bool' object is not subscriptable
Local variables in innermost frame:
self: <__main__.MPDWrapper object at 0x7f365b81ba50>
force: False
old_status: False
old_position: 228.723
old_time: 1580885354
new_status: {'volume': '40', 'repeat': '0', 'random': '1', 'single': '0', 'consume': '0', 'playlist': '2', …
```

Check new_status before updating _status

---

src/mpDris2.in.py

With this PR, one can use a tilde to represent the user's home directory.
In the docs for [os.path.expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser), it says this expansion only takes place when the character is at the front of the string, so this is an easy implementation.
I think it would be nice to have this for `music_dir` aswell, though I couldn't find the best place for it.
_Edit: fixed typo, added url to python docs._

Allow Host to contain a '~' in the configuration

---

src/mpDris2.in.py

The shebang already points to python3 so it doesn't make sense to have these compat shims in anyway.

Drop python2 support

---

src/mpDris2.in.py

As I said on #135, find_cover does not account for non-dir music "directories", such as archive files (`.zip`s etc), and causes a crash. This PR fixes that behavior.
Fixes #135

find_cover: Account for non-dir directories

---

src/mpdris2.desktop

systemd-xdg-autostart-generator in systemd >= 246 would generate a
systemd unit from the XDG autostart file, but this package already has
a mpDris2.service, making app-mpdris2-autostart.service redundant.
Similarly, GNOME would normally take responsibility for launching
any XDG autostarted services that systemd doesn't, but that's redundant
with mpDris2.service.

mpdris2.desktop: Disable if using systemd for session management

---

src/mpDris2.service.in

Commit d34b8821 only did this when started by the dbus-daemon using
traditional (non-systemd) activation, which seems odd when trying to
use a systemd-specific feature.

Log to systemd journal when started via systemd

---

src/mpDris2.in.py

I confess I'm not sure _when_ or _**how**_ it would happen, myself, but we received a [crashreporter log](https://bugzilla.redhat.com/show_bug.cgi?id=1963403) for the Fedora package indicating that the value of `self._currentsong` could in certain circumstances be a boolean value. (`False`, one presumes.):
```text
Version-Release number of selected component:
mpdris2-0.8-6.20200205git491588a.fc34
Additional info:
reporter:       libreport-2.14.0
cgroup:         0::/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-mpdris2-47029.scope
cmdline:        /usr/bin/python3 /usr/bin/mpDris2
crash_function: last_currentsong
exception_type: AttributeError
executable:     /usr/bin/mpDris2
interpreter:    python3-3.9.5-2.fc34.x86_64
kernel:         5.11.21-300.fc34.x86_64
runlevel: …
```

Protect access to last_currentsong

---

src/mpDris2.in.py

This PR adds MP4 cover art support based on the mutagen docs for MP4 tags. It assumes the first cover art (if any) is the front cover and instantiates its own `mutagen.id3.APIC` since the MP4 API doesn't provide one and `_create_temp_cover` expects one
Let me know if anything is problematic or should be changed!

Add mp4 cover art support

---

src/mpDris2.in.py

This PR adds support for finding cover art based on `music_dir` when using the local plugin from Mopidy. Only the first few lines of the diff matter, which parse the `local:track:[path/relative/to/music_dir.ext]` URL format that plugin gives over MPD metadata and prepends it with the configured `music_dir`
The rest of the diff de-indents everything else in the `find_cover` method since it now parses `song_path` early and returns if that fails (which allows for other adaptations to be made later, if for some reason that's necessary)
It works great in my testing with the rest of mpDris2 and this was my last local patch I have been running it with. Let me know if anything needs to be changed. Thank you all for this handy bit of software!

Add mopidy local url cover art support

---

README.md
src/mpDris2.conf
src/mpDris2.in.py

This adds a "cdprev" config option which makes the previous command behave more like most other music players: if playback is more than three seconds into a track, seek to the beginning, otherwise go to the previous track.
This option is named after a similar feature in mpc.

Add optional CD-like previous behavior

---

README.md
src/mpDris2.conf
src/mpDris2.in.py

This primarily adds the ability to format the notification's summary and
body for either the paused or playing states. Additionally, an option to
enable/disable notifications when the player is paused and an option for
notification timeout have been added.
~~The only remaining issue I have is that the format strings are in the style of `%%...%%` instead of mimicking `mpc`'s style of `%...%`. From what I've gathered, I'd need to disable interpolation in `ConfigParser()` but doing so removes the convenience of  detecting subsections. I'm not sure if what I have currently is good enough or if it's worth the trouble of trying to extract the values without interpolation.~~
Well that turned out easy.
This PR mostly implements https://github.com/eonpatapon/mpDris2/issues/148

Add many new options for notifications

---

src/mpDris2.in.py
src/mpDris2.service.in

When idle is available, the main purpose of the timer loop is to reconnect the
socket when it is disconnected.
An alternative is to allow systemd to handle this for us. We can bind the daemon
to the mpd service, so that it is started automatically with the mpd service.
Add a new command-line option `--managed`. If this is set, the daemon will exit
cleanly instead of attempting a reconnect loop, under the assmption that systemd
will restart it when mpd is available again.
Fixes #120
Also fixes #160 when managed by systemd - the service is only started when MPD is
Improves #133 when using systemd - the timer is no longer enabled

Add --managed option to disable timer
